-- Copy dan Paste semua kode ini ke "SQL Editor" di Dashboard Supabase Anda --

-- 1. Buat Tabel Strategies (Untuk menyimpan Equity & Drawdown)
CREATE TABLE IF NOT EXISTS public.strategies (
    symbol TEXT PRIMARY KEY,
    strategy_name TEXT NOT NULL,
    initial_balance NUMERIC NOT NULL,
    current_equity NUMERIC NOT NULL,
    peak_equity NUMERIC NOT NULL,
    max_drawdown NUMERIC DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buat Tabel Trades (Untuk menyimpan riwayat trading)
-- UPDATE: Menambahkan kolom alert_message untuk pesan custom
CREATE TABLE IF NOT EXISTS public.trades (
    id TEXT PRIMARY KEY,
    symbol TEXT REFERENCES public.strategies(symbol),
    strategy_name TEXT,
    side TEXT CHECK (side IN ('buy', 'sell')),
    entry_price NUMERIC,
    stop_loss NUMERIC,
    take_profit NUMERIC,
    alert_message TEXT, -- Kolom baru untuk menyimpan pesan custom dari TV
    entry_time TIMESTAMPTZ DEFAULT NOW(),
    exit_time TIMESTAMPTZ,
    exit_price NUMERIC,
    position_size NUMERIC,
    risk_amount NUMERIC,
    pnl NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED'))
);

-- OTOMATIS TAMBAHKAN KOLOM JIKA TABEL SUDAH ADA
DO $$
BEGIN
    ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS alert_message TEXT;
EXCEPTION
    WHEN duplicate_column THEN RAISE NOTICE 'column alert_message already exists in trades.';
END $$;

-- 3. Tabel Push Subscriptions (Untuk menyimpan token notifikasi HP User)
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint TEXT UNIQUE NOT NULL,
    keys JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Masukkan Data Awal (Reset Strategy jika belum ada)
INSERT INTO strategies (symbol, strategy_name, initial_balance, current_equity, peak_equity)
VALUES 
('BTCUSD', 'Strategy_BTC', 2400, 2400, 2400),
('XAUUSD', 'Strategy_XAU', 2900, 2900, 2900)
ON CONFLICT (symbol) DO NOTHING;

-- 5. Aktifkan Realtime
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE strategies;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE trades;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- 6. Konfigurasi Keamanan (RLS)
ALTER TABLE public.strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Reset Policy
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."strategies";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."trades";
DROP POLICY IF EXISTS "Enable insert for all users" ON "public"."push_subscriptions";
DROP POLICY IF EXISTS "Enable read for all users" ON "public"."push_subscriptions";

-- Izinkan akses
CREATE POLICY "Enable read access for all users" ON "public"."strategies" AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."trades" AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Enable insert for all users" ON "public"."push_subscriptions" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

-- LOGIKA WEBHOOK RPC (Untuk Simulator / Testing App)
CREATE OR REPLACE FUNCTION handle_webhook(payload json)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_symbol text;
  v_event text;
  v_side text;
  v_entry_price numeric;
  v_stop_loss numeric;
  v_take_profit numeric;
  v_trade_id text;
  v_alert_message text;
  v_strategy record;
  v_risk_amount numeric;
  v_position_size numeric;
  v_pnl numeric;
  v_open_trade record;
  v_new_equity numeric;
  v_peak_equity numeric;
  v_drawdown numeric;
  v_risk_per_trade numeric := 0.01; 
BEGIN
  v_symbol := payload->>'symbol';
  v_event := payload->>'event';
  v_alert_message := payload->>'alert_message'; -- Tangkap pesan custom
  
  SELECT * INTO v_strategy FROM strategies WHERE symbol = v_symbol;
  IF NOT FOUND THEN
    RETURN json_build_object('error', 'Strategy not found for symbol: ' || COALESCE(v_symbol, 'null'));
  END IF;

  IF v_event = 'entry' THEN
     v_side := payload->>'side';
     v_entry_price := (payload->>'entry_price')::numeric;
     v_stop_loss := (payload->>'stop_loss')::numeric;
     v_take_profit := (payload->>'take_profit')::numeric;
     v_trade_id := payload->>'trade_id';

     v_risk_amount := v_strategy.current_equity * v_risk_per_trade;
     
     IF ABS(v_entry_price - v_stop_loss) > 0 THEN
        v_position_size := v_risk_amount / ABS(v_entry_price - v_stop_loss);
     ELSE
        v_position_size := 0;
     END IF;

     INSERT INTO trades (id, symbol, strategy_name, side, entry_price, stop_loss, take_profit, position_size, risk_amount, status, entry_time, alert_message)
     VALUES (
        COALESCE(v_trade_id, 't_' || extract(epoch from now())::text), 
        v_symbol, 
        v_strategy.strategy_name, 
        v_side, 
        v_entry_price, 
        v_stop_loss, 
        v_take_profit, 
        v_position_size, 
        v_risk_amount, 
        'OPEN', 
        NOW(),
        v_alert_message
     );

     RETURN json_build_object('status', 'success', 'message', 'Entry recorded', 'size', v_position_size);

  ELSIF v_event = 'exit' THEN
     SELECT * INTO v_open_trade FROM trades WHERE symbol = v_symbol AND status = 'OPEN' LIMIT 1;
     
     IF NOT FOUND THEN
        RETURN json_build_object('status', 'warning', 'message', 'No open trade found to close');
     END IF;

     IF v_open_trade.side = 'buy' THEN
        v_pnl := ((payload->>'exit_price')::numeric - v_open_trade.entry_price) * v_open_trade.position_size;
     ELSE
        v_pnl := (v_open_trade.entry_price - (payload->>'exit_price')::numeric) * v_open_trade.position_size;
     END IF;

     v_new_equity := v_strategy.current_equity + v_pnl;
     v_peak_equity := GREATEST(v_strategy.peak_equity, v_new_equity);
     v_drawdown := ((v_peak_equity - v_new_equity) / v_peak_equity) * 100;

     UPDATE strategies SET 
        current_equity = v_new_equity, 
        peak_equity = v_peak_equity, 
        max_drawdown = GREATEST(v_strategy.max_drawdown, v_drawdown),
        updated_at = NOW()
     WHERE symbol = v_symbol;

     UPDATE trades SET 
        status = 'CLOSED', 
        exit_price = (payload->>'exit_price')::numeric, 
        exit_time = NOW(), 
        pnl = v_pnl 
     WHERE id = v_open_trade.id;

     RETURN json_build_object('status', 'success', 'message', 'Exit recorded', 'pnl', v_pnl, 'new_equity', v_new_equity);
  END IF;

  RETURN json_build_object('error', 'Unknown event type');
EXCEPTION WHEN OTHERS THEN
  RETURN json_build_object('error', SQLERRM);
END;
$$;